services:
  nuxt:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.dev
    image: nuxt-dev
    container_name: nuxt-dev
    volumes:
      - ..:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  wordpress:
    image: wordpress
    container_name: wordpress-dev
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      # - wordpress:/var/www/html
      - ./themes:/var/www/html/wp-content/themes/
      - ./plugins:/var/www/html/wp-content/plugins/

  db:
    image: mysql:8.0
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    # volumes:
    #   - db:/var/lib/mysql

volumes:
  nuxt:
  wordpress:
  db:
